# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/BatteryStateArray.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/BehaviorFault.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/EStopStateArray.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/FootStateArray.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/LeaseArray.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/LeaseOwner.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/Metrics.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/SystemFault.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/WiFiState.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/BatteryState.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/BehaviorFaultState.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/EStopState.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/Feedback.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/FootState.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/Lease.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/LeaseResource.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/PowerState.msg;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg/SystemFaultState.msg"
services_str = ""
pkg_name = "spot_msgs"
dependencies_str = "std_msgs;geometry_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "spot_msgs;/home/mrjohd/Quadrupeds_ws/src/robots/descriptions/spot_ros/spot_msgs/msg;std_msgs;/opt/ros/melodic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/melodic/share/geometry_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
