#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/mrjohd/Quadrupeds_ws/devel_isolated/robot_state_plugin:/home/mrjohd/Quadrupeds_ws/devel_isolated/data_generator:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_gazebo:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_description:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_core:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_control:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_teleop:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_setup_assistant:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_navigation:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_gazebo:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_msgs:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_description:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_config:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_bringup:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_simple_description:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_config:/opt/ros/melodic:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt'
export LD_LIBRARY_PATH='/home/mrjohd/Quadrupeds_ws/devel_isolated/data_generator/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_gazebo/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_description/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_core/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_control/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_teleop/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_setup_assistant/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_navigation/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_gazebo/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_msgs/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_description/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_config/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_bringup/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_simple_description/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_config/lib:/opt/ros/melodic/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt/lib/x86_64-linux-gnu:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt/lib:/usr/lib/x86_64-linux-gnu/'
export PATH='/opt/ros/melodic/bin:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt/bin:/home/mrjohd/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/mrjohd/Quadrupeds_ws/devel_isolated/data_generator/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_gazebo/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_description/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_core/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_control/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_teleop/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_setup_assistant/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_navigation/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_gazebo/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_msgs/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_description/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_config/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_bringup/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_simple_description/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_config/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt/lib/pkgconfig:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_msgs/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt/lib/python2.7/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/mrjohd/Quadrupeds_ws/devel_isolated/robot_state_plugin/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/mrjohd/Quadrupeds_ws/src/controller/robot_state_plugin:$ROS_PACKAGE_PATH"