set(_CATKIN_CURRENT_PACKAGE "data_generator")
set(data_generator_VERSION "0.0.0")
set(data_generator_MAINTAINER "mrjohd <mrjohd@todo.todo>")
set(data_generator_PACKAGE_FORMAT "2")
set(data_generator_BUILD_DEPENDS "champ_msgs" "geometry_msgs" "ros_cpp" "std_msgs" "sensor_msgs" "nav_msgs" "visualization_msgs" "tf" "tf2")
set(data_generator_BUILD_EXPORT_DEPENDS "champ_msgs" "geometry_msgs" "ros_cpp" "std_msgs")
set(data_generator_BUILDTOOL_DEPENDS "catkin")
set(data_generator_BUILDTOOL_EXPORT_DEPENDS )
set(data_generator_EXEC_DEPENDS "champ_msgs" "geometry_msgs" "ros_cpp" "std_msgs" "sensor_msgs" "nav_msgs" "visualization_msgs")
set(data_generator_RUN_DEPENDS "champ_msgs" "geometry_msgs" "ros_cpp" "std_msgs" "sensor_msgs" "nav_msgs" "visualization_msgs")
set(data_generator_TEST_DEPENDS )
set(data_generator_DOC_DEPENDS )
set(data_generator_URL_WEBSITE "")
set(data_generator_URL_BUGTRACKER "")
set(data_generator_URL_REPOSITORY "")
set(data_generator_DEPRECATED "")