set(_CATKIN_CURRENT_PACKAGE "xpp_champ")
set(xpp_champ_VERSION "1.0.10")
set(xpp_champ_MAINTAINER "Juan Jimeno <jimenojmm@gmail.com>")
set(xpp_champ_PACKAGE_FORMAT "2")
set(xpp_champ_BUILD_DEPENDS "xacro" "roscpp" "xpp_vis")
set(xpp_champ_BUILD_EXPORT_DEPENDS "xacro" "roscpp" "xpp_vis")
set(xpp_champ_BUILDTOOL_DEPENDS "catkin")
set(xpp_champ_BUILDTOOL_EXPORT_DEPENDS )
set(xpp_champ_EXEC_DEPENDS "xacro" "roscpp" "xpp_vis")
set(xpp_champ_RUN_DEPENDS "xacro" "roscpp" "xpp_vis")
set(xpp_champ_TEST_DEPENDS )
set(xpp_champ_DOC_DEPENDS )
set(xpp_champ_URL_WEBSITE "")
set(xpp_champ_URL_BUGTRACKER "")
set(xpp_champ_URL_REPOSITORY "")
set(xpp_champ_DEPRECATED "")