#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_champ:/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_vis:/home/mrjohd/Quadrupeds_ws/devel_isolated/towr_ros:/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_states:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_base:/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_msgs:/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp:/home/mrjohd/Quadrupeds_ws/devel_isolated/spot_viz:/home/mrjohd/Quadrupeds_ws/devel_isolated/spot_msgs:/home/mrjohd/Quadrupeds_ws/devel_isolated/spot_driver:/home/mrjohd/Quadrupeds_ws/devel_isolated/spot_description:/home/mrjohd/Quadrupeds_ws/devel_isolated/robot_state_plugin:/home/mrjohd/Quadrupeds_ws/devel_isolated/data_generator:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_gazebo:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_description:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_core:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_control:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_teleop:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_setup_assistant:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_navigation:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_gazebo:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_msgs:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_description:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_config:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_bringup:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_simple_description:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_config:/opt/ros/melodic:/home/mrjohd/Quadrupeds_ws/devel_isolated/towr:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt'
export LD_LIBRARY_PATH='/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_champ/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_vis/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/towr_ros/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_states/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_base/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_msgs/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/spot_viz/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/spot_msgs/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/spot_driver/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/spot_description/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/robot_state_plugin/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/data_generator/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_gazebo/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_description/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_core/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/cheetah_control/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_teleop/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_setup_assistant/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_navigation/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_gazebo/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_msgs/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_description/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_config/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ_bringup/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/champ/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_simple_description/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/anymal_b_config/lib:/opt/ros/melodic/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/towr/lib:/home/mrjohd/Quadrupeds_ws/devel_isolated/ifopt/lib:/usr/lib/x86_64-linux-gnu/'
export PKG_CONFIG_PATH="/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_champ/lib/pkgconfig:$PKG_CONFIG_PATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/mrjohd/Quadrupeds_ws/devel_isolated/xpp_champ/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/mrjohd/Quadrupeds_ws/src/planner/xpp/robots/xpp_champ:$ROS_PACKAGE_PATH"