set(_CATKIN_CURRENT_PACKAGE "xpp_popi")
set(xpp_popi_VERSION "1.0.10")
set(xpp_popi_MAINTAINER "Alexander W. Winkler <alexander.w.winkler@gmail.com>")
set(xpp_popi_PACKAGE_FORMAT "2")
set(xpp_popi_BUILD_DEPENDS "xacro" "roscpp" "xpp_vis")
set(xpp_popi_BUILD_EXPORT_DEPENDS "xacro" "roscpp" "xpp_vis")
set(xpp_popi_BUILDTOOL_DEPENDS "catkin")
set(xpp_popi_BUILDTOOL_EXPORT_DEPENDS )
set(xpp_popi_EXEC_DEPENDS "xacro" "roscpp" "xpp_vis")
set(xpp_popi_RUN_DEPENDS "xacro" "roscpp" "xpp_vis")
set(xpp_popi_TEST_DEPENDS )
set(xpp_popi_DOC_DEPENDS )
set(xpp_popi_URL_WEBSITE "http://github.com/leggedrobotics/xpp")
set(xpp_popi_URL_BUGTRACKER "http://github.com/leggedrobotics/xpp/issues")
set(xpp_popi_URL_REPOSITORY "")
set(xpp_popi_DEPRECATED "")